# Generated by Django 4.2.7 on 2026-01-18 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('presentation', 'Presentation')], help_text='Type of artifact', max_length=20)),
                ('artifact_labels', models.CharField(blank=True, help_text='Comma-separated labels for keyword search', max_length=500)),
                ('file', models.FileField(help_text='Upload file', upload_to='artifacts/')),
                ('name', models.CharField(help_text='Artifact name/title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the artifact')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this communication')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Investor name', max_length=255)),
                ('email', models.EmailField(help_text='Investor email address', max_length=254, unique=True)),
                ('labels', models.CharField(blank=True, help_text="Comma-separated labels for search (e.g., 'VC, Tech, Series-A')", max_length=500)),
                ('address', models.TextField(blank=True, help_text='Investor address')),
                ('details', models.TextField(blank=True, help_text='Additional details about the investor')),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount in Rs.', max_digits=15)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, help_text='Username who last updated', max_length=150)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='ResponseFunding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('pending', 'Pending')], default='pending', help_text='Response status from investor', max_length=10)),
                ('amount_offered', models.DecimalField(decimal_places=2, default=0, help_text='Amount offered by investor (Rs.)', max_digits=15)),
                ('notes', models.TextField(blank=True, help_text='Response notes/comments')),
                ('response_date', models.DateTimeField(help_text='When response was received')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.communicationlog')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_responses', to=settings.AUTH_USER_MODEL)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_responses', to='core.investor')),
            ],
            options={
                'verbose_name': 'Response/Funding',
                'verbose_name_plural': 'Responses/Funding',
                'ordering': ['-response_date'],
            },
        ),
        migrations.CreateModel(
            name='EmailDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Unique draft name (e.g., 'pitchdeck', 'intro_email')", max_length=100, unique=True)),
                ('subject', models.CharField(help_text='Email subject line', max_length=255)),
                ('body', models.TextField(help_text='Email body content (supports HTML)')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('artifacts', models.ManyToManyField(blank=True, help_text='Select artifacts to attach to this email', related_name='email_drafts', to='core.artifact')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='draft',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='core.emaildraft'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='core.investor'),
        ),
        migrations.AddField(
            model_name='communicationlog',
            name='sent_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_communications', to=settings.AUTH_USER_MODEL),
        ),
    ]
